name: Build and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive Files
        run: |
          zip -r nextjs-build.zip .next public node_modules package.json package-lock.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build.zip
          path: nextjs-build.zip

      - name: Set unique image tag
        id: unique-image-tag
        run: echo "::set-output name=tag::prod-${{ github.sha }}"

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: danielneset/idata2306:${{ steps.unique-image-tag.outputs.tag }}
